[package]
name = "schlang-lib"
version = "0.1.0"
edition = "2021"

[dependencies]
lalrpop-util = { version = "0.22.0", features = ["lexer", "unicode"] }
thiserror = "2.0.4"

[build-dependencies]
lalrpop = "0.22.0"
